Rebranded Allure reports and adapted to Github Actions (#266)

diff --git a/bin/ibexareport b/bin/ibexareport
--- a/bin/ibexareport
+++ b/bin/ibexareport
@@ -2,10 +2,10 @@
 # Examples of use:
 #
 # Default use in Travis builds:
-#   bin/ezreport
+#   bin/ibexareport
 #
 # Specify non-default SSH key and tested bundle name (required to run script outside Travis runs)
-#   bin/ezreport -i=path/to/sshkey -r=BehatBundle
+#   bin/ibexareport -i=path/to/sshkey -r=BehatBundle
 # Reports generated in this way will be hosted on the server in BehatBundle/manual/time_stamp directory
 
 SSH_KEY_PATH='vendor/ezsystems/behatbundle/bin/.travis/rsa_allure'
@@ -16,7 +16,7 @@ HOST_NAME='allure.ez.no'
 usage(){
 echo -e "\
 Usage:
-\t ezreport [OPTIONS...]
+\t ibexareport [OPTIONS...]
 
 Options:
 
@@ -28,8 +28,8 @@ Options:
 
  # Error message
 error(){
-    echo "ezreport: invalid option -- '$1'";
-    echo "Try 'ezreport -h' for more information.";
+    echo "ibexareport: invalid option -- '$1'";
+    echo "Try 'ibexareport -h' for more information.";
     exit 1;
 }
 
@@ -38,7 +38,7 @@ cd ${ALLURE_BUILD_PATH}
 TIMESTAMP=$(date "+h%H-m%M")
 if [ -z $REPOSITORY_NAME ];
 then
-    REPORT_NAME="$(echo $TRAVIS_REPO_SLUG | cut -d'/' -f 2).$TRAVIS_JOB_NUMBER";
+    REPORT_NAME="$(echo $GITHUB_REPOSITORY | cut -d'/' -f 2).$GITHUB_RUN_ID.$GITHUB_RUN_NUMBER";
 else
     DATESTAMP=$(date "+%Y-%m-%d")
     REPORT_NAME="$REPOSITORY_NAME.manual.$DATESTAMP";
@@ -50,15 +50,15 @@ cd -
 }
 
 send_report_to_server(){
-sftp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i $SSH_KEY_PATH allure@$HOST_NAME:incoming/ <<< $"put ${ALLURE_BUILD_PATH}${ZIP_FILENAME_EX}" 1> /dev/null
+sftp -o StrictHostKeyChecking=no -q -o ConnectTimeout=10 -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i $SSH_KEY_PATH allure@$HOST_NAME:incoming/ <<< $"put ${ALLURE_BUILD_PATH}${ZIP_FILENAME_EX}" 1> /dev/null
 
-if [ $? -ne 0 ];
-then echo "Failure occured when uploading the report";
-else
-    ADDRESS_PATH="$(echo $ZIP_FILENAME | sed 's/\./\//g')"
-    WEB_ADDRESS="http://$HOST_NAME/$ADDRESS_PATH"
-    echo "See the report on ${WEB_ADDRESS}"
+if [ $? -ne 0 ]; then
+    exit 1
 fi
+
+ADDRESS_PATH="$(echo $ZIP_FILENAME | sed 's/\./\//g')"
+WEB_ADDRESS="http://$HOST_NAME/$ADDRESS_PATH"
+echo "$WEB_ADDRESS"
 }
 
 process_report(){
